### ISSUE TITLE
数学関数

### ISSUE THREAD

**Issue by quartorz** [LoliGothick/Interval-Analysis#2]
`std::sqrt`以外の数学関数はcorrect roundingである保証はないはずなので、`sin`などを標準ライブラリでの計算結果に対して`downward`や`upward`を行うという実装にするのは問題があると思います。

**Comment by LoliGothick** [comment]
rounding control に関しては問題だらけであることがわかってきたので修正中であります

**Comment by LoliGothick** [comment]
Fixed this Issue with Update Ver. 3.0.0 .
Using fesetround instead of downward or upward.

**Comment by mskashi** [comment]
sqrt以外の数学関数については、丸めモードをnearest以外にしたときの動作は実装依存であり、期待通りに(downwardのときは真値以下に、upwardのときは真値以上に)なるとは限りません。というか、試してみれば分かりますが現状ほぼすべての環境において期待通りに動きません。従って、fesetroundを使った区間数学関数の実装も問題があります。fesetroundが期待通り動くのは加減乗除と平方根だけです。

**Comment by LoliGothick** [comment]
fmaは問題ないのでしょうか？

**Comment by mskashi** [comment]
fmaはIEEE754には規定がないので、これまた実装依存だと思います。実際には、Haswell以降のハードウェア実装されているものに関しては、丸めモードに従って動いているようです。ソフトウェアエミュレーションの場合はかなり怪しいと思います。

**Comment by mskashi** [comment]
sqrt以外の数学関数で区間演算を実現するには、現状

* 自分で(Taylor展開等を使って)実装する
* crlibm ( http://lipforge.ens-lyon.fr/www/crlibm/ )を使う

の二通りが考えられるでしょうか。

**Comment by LoliGothick** [comment]
丁寧に改善案まで出していただいて、ありがとうございます
テイラー展開で実装する方向ですすめています

**Comment by mskashi** [comment]
closeした話題にコメントを付けたりして済みませんでした。区間演算ライブラリにはとても期待しています!
